# Define the Railway project
[project]
name = "Synthex"

# Define the service for the web application
[services.web]
# Path to the web application in your Turborepo
path = "apps/web"

# Commands to build and start the web app
build = "pnpm install && pnpm turbo run build --filter=web"
start = "pnpm turbo run start --filter=web"

# Optional: Set the install command if you want Railway to use pnpm instead of npm by default
install = "pnpm install"
